version: "3.7"

services:
  php:
    image: php:8.1-fpm-alpine
    volumes:
      - .:/var/www/html

  nginx:
    image: nginx:1.21-alpine
    volumes:
      - .:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    ports:
      - "3070:80"

  redis:
    image: redis:alpine
    ports:
      - "63791:6379"